// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventStream = "event_stream"

// EventStream mapped from table <event_stream>
type EventStream struct {
	ID            int64       `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	StreamID      string      `gorm:"column:stream_id;type:character varying(255);not null;uniqueIndex:event_stream_stream_id_stream_version_key,priority:1" json:"stream_id"`
	StreamVersion int32       `gorm:"column:stream_version;type:integer;not null;uniqueIndex:event_stream_stream_id_stream_version_key,priority:2;default:1" json:"stream_version"`
	EventID       string      `gorm:"column:event_id;type:uuid;not null" json:"event_id"`
	CreatedAt     time.Time   `gorm:"column:created_at;type:timestamp without time zone;not null;default:now()" json:"created_at"`
	Event         *EventStore `gorm:"foreignKey:event_id;references:event_id" json:"event"`
}

// TableName EventStream's table name
func (*EventStream) TableName() string {
	return TableNameEventStream
}
